### ISSUE TITLE
Missing core-js/modules/es7.object.entries

### ISSUE THREAD

**Issue by benwaffle** [jaydenseric/apollo-upload-server#103] opened 2018-08-15 20:11 UTC
```
Error: Cannot find module 'core-js/modules/es7.object.entries'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/me/project/node_modules/apollo-upload-server/lib/middleware.js:14:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

using the latest version of apollo server

<img width="677" alt="image" src="https://user-images.githubusercontent.com/1713819/44170646-fb3e1d00-a0a5-11e8-93fc-d3513def957f.png">

**Comment by mike-marcacci** [comment] 2018-08-15 20:27
@benwaffle is this showing up when using apollo-server by itself (and its bundled apollo-upload-server) or are you using this library directly?

**Comment by mike-marcacci** [comment] 2018-08-15 20:29
Assuming you're on apollo-upload-server 5.0.0, this should be [present via the `@babel/runtime#7.0.0-beta.40` dependency](https://github.com/babel/babel/blob/v7.0.0-beta.40/packages/babel-runtime/package.json), which was used in the transpilation and testing.

**Comment by jaydenseric** [comment] 2018-08-16 01:30
Babel recently had a big breaking change to the way Babel runtime works, and published it as a new prelease of the same major version as before (`7`). Packages that had specified the dependency with a `^` are now broken. We have a new version on the way, although you will need to do a little refactoring to the new API once it's out 🙏

**Comment by jaydenseric** [comment] 2018-08-16 01:31
I think you won't have the issue with `apollo-upload-server@6.0.0-alpha.1`.

**Comment by jaydenseric** [comment] 2018-08-16 03:58
Closing since the issue is fixed in the current release.

**Closed by jaydenseric** 2018-08-16 03:58 UTC
Labels: bug

**Comment by benwaffle** [comment] 2018-08-16 13:48
@mike-marcacci i'm using apollo-server, not apollo-upload-server directly

**Comment by jaydenseric** [comment] 2018-08-16 14:27
@benwaffle you're stuck, nothing you can do but wait for Apollo to update their `apollo-upload-server` dependency.

**Comment by jaydenseric** [comment] 2018-08-16 14:31
Well, actually you can make sure your `package-lock.json` has the exact dependency you need in it.

**Comment by benwaffle** [comment] 2018-08-16 14:44
installing core-js manually fixes the issue

**Comment by jwoptio** [comment] 2018-08-16 16:14
Using yarn you can specify specific sub-dependency versions using the resolutions block in your `package.json`:

ie:
```
  "resolutions": {
    "apollo-server-lambda/**/apollo-upload-server": "6.0.0-alpha.1"
  }
```

**Comment by benwaffle** [comment] 2018-08-17 00:09
thanks, but i'm using npm

**Comment by andyrichardson** [comment] 2018-08-17 10:10
@jaydenseric Apollo likely won't be updating to the _6.0.0-alpha.1_ release due to dropped support for Node 6.x.

Is a 5.0.1 release with core-js an option?

**Comment by abernix** [comment] 2018-08-20 13:13
@jaydenseric Would you accept a PR for a (proposed) v5.0.1, branched off the [`v5.0.0`](https://github.com/jaydenseric/apollo-upload-server/tree/v5.0.0) tag which switches `@babel/runtime` to `@babel/runtime-corejs2` (and the appropriate changes)?

I've staged what that would look like on a fork of this repository that I just made here: https://github.com/apollographql/apollo-upload-server/pull/1, and this seems to do the trick!  (Though `npm test` is exhibiting failures both before _and_ after my change, and I'm not sure what the reason is.)

**Comment by jaydenseric** [comment] 2018-08-20 13:16
There are other, critical reasons to upgrade other than the recent dependency issue. People can crash your server process by sending a malformed request. Or a file too large, and other bugs fixed in the newest releases.

**Comment by abernix** [comment] 2018-08-20 15:26
Those are certainly compelling reasons to upgrade!
