### ISSUE TITLE
core-js should be listed as a dependency

### ISSUE THREAD

**Issue by fleveillee** [jaydenseric/apollo-upload-server#106] opened 2018-08-16 22:07 UTC
When trying to run through apollo-server I get this error.

`Error: Cannot find module 'core-js/modules/es7.object.entries'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/fleveillee/Projects/yuAPI/node_modules/apollo-upload-server/lib/middleware.js:14:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/fleveillee/Projects/yuAPI/node_modules/apollo-upload-server/lib/index.js:19:19)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)`

 Does not happen to me in dev since I use babel, that requires core-js only if I run `yarn --production`

Workaround: Temporarily adde 'core-js' as a prod requirement

/lib/middleware.js line 14
require('core-js/modules/es7.object.entries')

**Comment by mike-marcacci** [comment] 2018-08-16 22:10
This is a duplicate of #103. @jaydenseric even though this is fixed, perhaps we should publish a `v5.0.1` which is identical to `v5.0.0` but specifies this as a dependency?

**Comment by jaydenseric** [comment] 2018-08-17 13:40
This issue is fixed in the last two published releases. As mentioned, this issue duplicates https://github.com/jaydenseric/apollo-upload-server/issues/103 so lets focus discussion there 🙏

**Closed by jaydenseric** 2018-08-17 13:40 UTC

**Comment by fleveillee** [comment] 2018-08-18 14:35
Thanks a lot for the prompt response!
