### ISSUE TITLE
"Must provide Document" Error

### ISSUE THREAD

**Issue by Tjark-Kuehl** [jaydenseric/apollo-upload-server#18] opened 2017-11-12 20:34 UTC
Hi there,
today I was trying to implement a Avatar Upload system for user profiles.
So I came across apollo-upload server and client.
After implementing it like shown in the examples I'm getting this error and dont know how to solve it
`Error: Must provide document
    at invariant (/Users/tjarkkuehl/Desktop/semtexxx.de-website/server/node_modules/graphql/jsutils/invariant.js:18:11)
    at Object.validate (/Users/tjarkkuehl/Desktop/semtexxx.de-website/server/node_modules/graphql/validation/validate.js:58:34)
    at doRunQuery (/Users/tjarkkuehl/Desktop/semtexxx.de-website/server/node_modules/apollo-server-express/node_modules/apollo-server-core/src/runQuery.ts:143:30)
    at /Users/tjarkkuehl/Desktop/semtexxx.de-website/server/node_modules/apollo-server-express/node_modules/apollo-server-core/src/runQuery.ts:69:39
    at <anonymous>`

# Server Setup

## Index 
```

import { apolloUploadExpress } from 'apollo-upload-server'

app.use(
    '/graphql',
    bodyParser.json(),
    apolloUploadExpress({uploadDir: './user_upload/'})
)
```

## Schema

```
input Upload {
    name: String!
    type: String!
    size: Int!
    path: String!
}

type Mutation {
    uploadAvatar(file: Upload!) : Boolean!
}
```

## Resolver

```
uploadAvatar: (parent, args, context) => {
    console.log('Worked!')
    return true
}
```

# Client Setup

## Index

```
import { createUploadLink } from 'apollo-upload-client'

const link = createUploadLink({
    uri: `http://${config.graphqlAddress}:${config.graphqlPort}/graphql`
})

export const apolloClient = new ApolloClient({
    link: from([
        link,
        authMiddleware,
        authAfterware
    ]),
    cache: new InMemoryCache(),
    connectToDevTools: true
})
```

## Profile.vue

```
<input class="select_file_action"
                           type="file"
                           @change="tryChangeAvatar($event)">

this.$apollo.provider.defaultClient.mutate({
    mutation: gql`
    mutation ($file: Upload!) {
        uploadAvatar(file: $file)
    }`,
    variables: {
        file: target.files[0]
    }
})
```

**Comment by jaydenseric** [comment] 2017-11-12 22:18
I have not seen this error before 🤔

To start with, it's always good to confirm [the right version of node](https://github.com/jaydenseric/apollo-upload-server/blob/v2.0.4/package.json#L58) is running.

Is `graphqlExpress()` really missing in the middleware, or is that just a copy-paste error?

**Comment by Tjark-Kuehl** [comment] 2017-11-13 07:02
I'm running Node Version 8.5.0 and this is how my complete server imports look like
```
import connect from 'connect'
import cors from 'cors'
import bodyParser from 'body-parser'
import { execute, subscribe } from 'graphql'
import { graphqlConnect, graphiqlConnect } from 'apollo-server-express'
import { SubscriptionServer } from 'subscriptions-transport-ws'
import { apolloUploadExpress } from 'apollo-upload-server'
import { createServer } from 'http'
import jwt from 'jsonwebtoken'
import helmet from 'helmet'
```

I'm using apollo-server-express.
Do you think it might be a problem with express ? So that I cant upload a file because I'm not allowed to

**Comment by jaydenseric** [comment] 2017-11-16 01:00
The request looks ok.

It looks like you are not using express. I don't know how your middleware fits together in this situation.

If you add a custom debug middleware right between `apolloUploadExpress` and Apollo server, what does the re-assembled request look like?

**Comment by jaydenseric** [comment] 2017-11-19 10:41
Closing because the issue is currently not reproducible, and [the entire API is about to change](https://github.com/jaydenseric/apollo-upload-server/pull/22) anyway.

Feel free to continue the discussion if anything comes to light 🙂

**Closed by jaydenseric** 2017-11-19 10:41 UTC
