### ISSUE TITLE
Large image uploads crashing

### ISSUE THREAD

**Issue by brianlovin** [jaydenseric/apollo-upload-server#6] opened 2017-06-15 21:30 UTC
<img width="720" alt="screenshot 2017-06-15 14 28 55" src="https://user-images.githubusercontent.com/1923260/27202599-136b78d8-51d7-11e7-8a47-70c718d4f004.png">

Everything on this library has been working wonderfully, so first of all: thank you so much! 

I noticed recently that we're failing on large image uploads (somewhere in the range of 3mb+) on the server side. Above is a log on the server.

Is this an inherent issue with post requests coming through gql? Or is there something we should be doing to handle larger images better?

Thank you!

**Comment by jaydenseric** [comment] 2017-06-16 01:46
Great report, this is almost certainly the default `maxFieldsSize` [option of formidable](https://github.com/felixge/node-formidable#formidableincomingform) working.

I need large uploads to work too, so I'll get started on adding a new option for it to our API.

The reason we don't just pass through a formidable config object is to abstract the internal implementation – there is a real chance that formidable will be swapped out sometime in the future and it would be great if that were not a breaking change.

**Comment by jaydenseric** [comment] 2017-06-16 06:29
This is weirder than I thought. In theory, `maxFieldsSize` should not count the size of the actual files, so I'm not sure why you would get that error.

I have been testing < 1MB, 2.5MB and 12MB files and get something else weird happening. The < 1MB file works flawlessly while the larger ones somehow upload twice. This is in my actual app, which is using Koa and a few other things are going on too so I am trying to work out the cause.

**Comment by jaydenseric** [comment] 2017-06-16 07:17
So my double upload issue seems to be relating to something different about my project, because testing large files in [jaydenseric/apollo-upload-examples](https://github.com/jaydenseric/apollo-upload-examples) everything work fine. No sign of either issue.

**Comment by brianlovin** [comment] 2017-06-16 18:38
Thanks so much for digging in! To clarify, you're no longer seeing errors for large files failing? Any ideas why I'd be running into that original error?

**Comment by jaydenseric** [comment] 2017-06-17 06:35
I think there must be something unique about the setup of your project. It's hard to say without debugging the problematic code; I can't recreate the specific error in a simple project.

That warning is supposed to happen when the non-file fields of the multipart form are over 2MB. So if you're Mutation had huge amounts of text or something in it or something that would cause it.

I spent a day trying to work out my issue. Something about my use of MongoDB GridFS and large files is triggering the Koa middleware to run twice in a row. No idea why, I might even try upgrading Node from 8.1 to 8.1.1 because there are some timeout related bugfixes.

**Comment by jaydenseric** [comment] 2017-06-19 02:27
For those curious, updating Node.js from v8.1 to v8.1.2 fixed my issue. There were some nasty bugs introduced in Node 8 that have affected quite a few projects, i.e. HMR in Next.js.

@brianlovin any news on the error? I'll close this issue until it can be reproduced.

**Closed by jaydenseric** 2017-06-19 02:27 UTC

**Comment by brianlovin** [comment] 2017-07-19 17:34
Hey @jaydenseric - just wanted to follow up on this and let you know that I was doing something dumb which was causing this to crash. You mentioned this above, but just wanted to provide the feedback in case it ever comes up again:

I was accidentally sending a `FileReader().result()` in the form object - which of course sends a massive base64 encoded string in the payload. I was doing this because I'm doing optimistic client-side rendering of images using that `reader.result()`, but obviously I don't need to send that to the server.

The fix was to just make sure to not send that reader result over the wire. Duh :P

**Comment by jaydenseric** [comment] 2017-07-20 04:52
@brianlovin thanks for the update 🙂

**Comment by ifalldev** [comment] 2018-03-15 15:54
@brianlovin, what did you send instead of reader result base64?

**Comment by brianlovin** [comment] 2018-03-15 17:17
@ifalldev I think you just need to send the file directly from the input now - the client docs have it like this:

```js
export default graphql(gql`
  mutation($file: Upload!) {
    uploadFile(file: $file) {
      id
    }
  }
`)(({ mutate }) => (
  <input
    type="file"
    required
    onChange={({ target: { validity, files: [file] } }) =>
      validity.valid && mutate({ variables: { file } })
    }
  />
))
```

**Comment by ifalldev** [comment] 2018-03-16 14:21
Thank you for your attention!

Nowadays browsers do not pass the attribute `path` or `filePath` neither `webKitRelativePath` for security purpose.

'Cause of that we have to use `FileReader` on client side to consume the `file.preview` (I'm using `React Dropzone`) and generate the result (`readAsBinaryString`) to send to back end (Express) and save on S3.

The problem was indeed the size of the payload, not exactly the `maxFieldSize` configuration on `apolloUploadExpress` middleware. To fix that, I putted the `limit` option on `bodyParser`, eg `bodyParser.json({ limit: 1024 * 1024 * 2000, type: 'application/json' })`. Now it works like a charm!

If you think that my solution could get better, _please tell me_!
